### ISSUE TITLE
Decompiling error (Java awt file problem) plz solve it....

### ISSUE THREAD

**Issue by yeasin6152** [Hax4us/Tmux-Bunch#22]
OpenJDK 64-Bit Server VM warning: Can't detect initial thread stack location - find_vma failed
I: Using Apktool 2.2.2-Black on cc.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /data/data/com.termux/files/home/Tmux-Bunch/1.apk
I: Regular manifest package...
I: Decoding file-resources...
Exception in thread "main" java.lang.UnsatisfiedLinkError: no awt in java.library.path
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2541)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:873)
        at java.base/java.lang.System.loadLibrary(System.java:1857)
        at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1358)
        at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1356)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1355)
        at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1388)
        at java.desktop/sun.awt.AppContext$2.run(AppContext.java:282)
        at java.desktop/sun.awt.AppContext$2.run(AppContext.java:271)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.awt.AppContext.initMainAppContext(AppContext.java:271)
        at java.desktop/sun.awt.AppContext.access$400(AppContext.java:140)
        at java.desktop/sun.awt.AppContext$3.run(AppContext.java:326)
        at java.desktop/sun.awt.AppContext$3.run(AppContext.java:309)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.awt.AppContext.getAppContext(AppContext.java:308)
        at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:152)
        at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
        at brut.androlib.res.decoder.Res9patchStreamDecoder.decode(Res9patchStreamDecoder.java:39)
        at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:120)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:87)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:262)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:132)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
        at brut.apktool.Main.cmdDecode(Main.java:166)
        at brut.apktool.Main.main(Main.java:81)

**Comment by yeasin6152** [comment]
which file ? Enter number of choice or 'x' to exit
2
I: Using Apktool 2.2.2-Black on cc.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /data/data/com.termux/files/home/Tmux-Bunch/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:58)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:132)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
        at brut.apktool.Main.cmdDecode(Main.java:166)
        at brut.apktool.Main.main(Main.java:81)

**Comment by TU4NN1CKN4M3** [comment]
Error: Unable to rebuild apk with apktool
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory

Can't sign in Tmux-Bunch v2.4
