### ISSUE TITLE
Tmux bunch error i cant bind any apk

### ISSUE THREAD

**Issue by mohamed16234** [Hax4us/Tmux-Bunch#26]
tmuxbunch: ./msfvenom: /usr/bin/env: bad interpreter: No such file or directory
signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
java.io.FileNotFoundException: /data/data/com.termux/files/home/Tmux-Bunch/unsign/fappybird34.apk (No such file or directory)
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.(ZipFile.java:215)
at java.util.zip.ZipFile.(ZipFile.java:145)
at java.util.jar.JarFile.(JarFile.java:154)
at java.util.jar.JarFile.(JarFile.java:133)
at com.android.signapk.SignApk.main(SignApk.java:949)
rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/fappybird34.apk': No such file or directory

We will met again :D , have a payload day..! 📢

press ENTER for main menu

**Comment by Deepanjan1995** [comment]
Sam problem Iam facing

**Comment by aymenem** [comment]
same problem i'm facing too :'(

**Comment by djaman** [comment]
Same Here

**Comment by gaksv** [comment]
i cant bind any apk

**Comment by Pryanshusharmad37** [comment]
Sam problem plese help us

**Comment by Pryanshusharmad37** [comment]
Same here help us plese

**Comment by RootSh311** [comment]
Use Tmux Bunch Oreo Version

**Comment by TechDossier** [comment]
*] Please wait while binding.......🕜

Using APK template: Fblite.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190817-24000-a257bb/original/AndroidManifest.xml
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
Bad system call
rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/fblite.apk': No such file or directory

**Comment by TechDossier** [comment]
**Tmux_Bunch Not Working**
** Am tried oreo version also**

*] Please wait while binding.......🕜

Using APK template: Fblite.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190817-24000-a257bb/original/AndroidManifest.xml
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
Bad system call
rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/fblite.apk': No such file or directory

**Comment by ng1nX4O4** [comment]
Please USE This Version Of Tmux Bunch

https://www.github.com/ng1nX4O4/Tmux-Bunch

Or Use Alternative
PatchApk v1.0

http://github.com/ng1nX4O4/PatchApk


And Let Me Know If You Are Facing Any Error

**Comment by Shubhendra-kushwaha** [comment]
Same issue
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190928-5595-7hirzv/original/AndroidManifest.xml
