### ISSUE TITLE
signing error in tmuxbunch

### ISSUE THREAD

**Issue by narayanchandrakar** [Hax4us/Tmux-Bunch#8]
![screenshot_2018-05-23-08-55-22-521_com termux](https://user-images.githubusercontent.com/37969085/40402021-10c7d548-5e67-11e8-81c4-96d4914c3eef.png)
I'm getting the error  plz help me

**Comment by ardyfeb** [comment]
Same too

**Comment by Hax4us** [comment]
Screenshot is too big ... Plz provide right screenshot for analysing

**Comment by ardyfeb** [comment]
Me too

**Comment by Hax4us** [comment]
Instead of `me too` can anybody give screenshot of error ?

**Comment by parminder7768** [comment]
HOw to add screenshot     ialso get this issue

**Comment by PETR03X** [comment]
oh I know the cause of this problem. this happens because the file smali in protect / max register from smali file .. its cause I do not know the exact problem happened in the recompiler process .. example apk facebook lite I tried to do manual injection payload and the results happened the same error .. but after i tried different application the error is not there .. aka process runs smoothly

**Comment by erick08** [comment]
[*] Please wait while binding.......🕜

WARNING: Nokogiri was built against LibXML version 2.9.7, but has dynamically loaded 2.9.8
Using APK template: teste.apk
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20180610-2819-p7n228/original/AndroidManifest.xml
-e  signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
/data/data/com.termux/files/home/Tmux-Bunch/.signapk: 9: /data/data/com.termux/files/home/Tmux-Bunch/.signapk: /data/data/com.termux/files/home/Tmux-Bunch/.bunch/openjdk/bin/java: not found
rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/teste.apk': No such file or directory

-e  We will met again :D , have a payload day..! 📢

-e  press ENTER for main menu

**Comment by erick08** [comment]
this is what happens @Hax4us

**Comment by Hax4us** [comment]
Can u try new release 
Install it again from https://github.com/Hax4us/Tmux-Bunch/blob/master/README.md

**Comment by erick08** [comment]
after I installed I chose the 6 option and this happened @ hax4us

**Comment by erick08** [comment]
[*] Please wait while binding.......🕜

WARNING: Nokogiri was built against LibXML version 2.9.7, but has dynamically loaded 2.9.8
Using APK template: Free_Fire__Battlegrounds_v1_16_0_APK_Mod_Money.apk
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
Error: Unable to find hook point in /data/data/com.termux/files/usr/tmp/d20180612-27640-1o9ebl4/original/smali*/com/veniosg/dir/android/FileManagerApplication.smali
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
java.io.FileNotFoundException: /data/data/com.termux/files/home/Tmux-Bunch/unsign/teste.apk (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:215)
        at java.util.zip.ZipFile.<init>(ZipFile.java:145)
        at java.util.jar.JarFile.<init>(JarFile.java:154)
        at java.util.jar.JarFile.<init>(JarFile.java:133)
        at com.android.signapk.SignApk.main(SignApk.java:949)
rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/teste.apk': No such file or directory

 We will met again :D , have a payload day..! 📢

 press ENTER for main menu

**Comment by larva007** [comment]
Please help me [*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
Error: Unable to find hook point in /data/data/com.termux/files/usr/tmp/d20181213-18776-5ph2am/original/smali*/com/facebook/lite/ClientApplicationSplittedShell.smali
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
java.io.FileNotFoundException: /data/data/com.termux/files/home/Tmux-Bunch/unsign/litenew.apk (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:215)
        at java.util.zip.ZipFile.<init>(ZipFile.java:145)
        at java.util.jar.JarFile.<init>(JarFile.java:154)
        at java.util.jar.JarFile.<init>(JarFile.java:133)
        at com.android.signapk.SignApk.main(SignApk.java:949)
rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/litenew.apk': No such file or directory

 We will met again :D , have a payload day..! 📢

 press ENTER for main menu

**Comment by rekcahkumar** [comment]
I tried terminal emulator still same help 
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190308-5295-z6ue3p/original/AndroidManifest.xml

**Comment by Shadowe07** [comment]
Begdecimal issue also affecting Tmux-Bunch error.anyone kindly resolve

**Comment by Shadowe07** [comment]
[*] Please wait while binding.......🕜

/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Traceback (most recent call last):
        29: from ./msfvenom:428:in `<main>'
        28: from ./msfvenom:55:in `framework'
        27: from ./msfvenom:36:in `init_framework'
        26: from ./msfvenom:18:in `require_deps'
        25: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        24: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        23: from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:18:in `<top (required)>'
        22: from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:18:in `require'
        21: from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `<top (required)>'
        20: from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `require'
        19: from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:1:in `<top (required)>'
        18: from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:1:in `require'
        17: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails.rb:11:in `<top (required)>'
        16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails.rb:11:in `require'
        15: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/application.rb:7:in `<top (required)>'
        14: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/application.rb:7:in `require'
        13: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/engine.rb:1:in `<top (required)>'
        12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/engine.rb:1:in `require'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/railtie.rb:2:in `<top (required)>'
        10: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/railtie.rb:2:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/configuration.rb:2:in `<top (required)>'
         8: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/configuration.rb:2:in `require'
         7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object.rb:12:in `<top (required)>'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object.rb:12:in `require'
         5: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/json.rb:4:in `<top (required)>'
         4: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/json.rb:4:in `require'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `<top (required)>'
         2: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `require'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'
/data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `require': dlopen failed: cannot locate symbol "rmpd_util_str_to_d" referenced by "/data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so"... - /data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so (LoadError)
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
java.io.FileNotFoundException: /data/data/com.termux/files
Issue facing after a fresh reinstall of metasploit from.Hax4us and solved none this error.still this issue affect Tmux-Bunch apk modding...kindly help

**Comment by Shadowe07** [comment]
Sir Plz Help And give us Solution for Begdecimal issue affecting Tmux-Bunch
